SELECT MEMBER_ID
        , MEMBER_NAME
        , GENDER
        , DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE MONTH(DATE_OF_BIRTH)=3
      AND TLNO IS NOT NULL
      AND GENDER ='W'
ORDER BY MEMBER_ID;

# DATE_FORMAT() 함수의 두번째 인자에서의 대문자, 소문자 구별해야함