SELECT SALES_DATE
       , PRODUCT_ID
       , USER_ID
       , SALES_AMOUNT
FROM (
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
           , PRODUCT_ID
           , USER_ID
           , SALES_AMOUNT
    FROM ONLINE_SALE
        UNION
    SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE
           , PRODUCT_ID
           , NULL AS USER_ID
           , SALES_AMOUNT
    FROM OFFLINE_SALE
) AS A
WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 3
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID

# UNION 중복 제거 합치기
# UNION ALL 중복 제거 없이 합치기